apiVersion: v1
kind: Service
metadata:
  name: frt-deployment
spec:
  selector:
    app: frt
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frt
  template:
    metadata:
      labels:
        app: frt
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: frt
        image: 900417077879.dkr.ecr.us-east-1.amazonaws.com/test3:61
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
