apiVersion: v1
kind: Service
metadata:
  name: aws-deployment
spec:
  selector:
    app: aws
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws
  template:
    metadata:
      labels:
        app: aws
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: aws
        image: 900417077879.dkr.ecr.us-east-1.amazonaws.com/test3:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
