apiVersion: v1
kind: Service
metadata:
  name: nana-deployment
spec:
  selector:
    app: nana2
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nana2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nana2
  template:
    metadata:
      labels:
        app: nana2
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: nana2
        image: 900417077879.dkr.ecr.us-east-1.amazonaws.com/test3
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
